[toolchain]
channel = "1.88"
components = [ "rust-src", "rustfmt", "llvm-tools", "clippy" ]
targets = [
    "thumbv7em-none-eabi",
    "thumbv7m-none-eabi",
    "thumbv6m-none-eabi",
    "thumbv7em-none-eabihf",
    "thumbv8m.main-none-eabihf",
]
